I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 158, in script
    lecturer "You are 15 minutes late!!!"
Exception: Sayer 'lecturer' is not defined.

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 158, in script
    lecturer "You are 15 minutes late!!!"
  File "renpy/ast.py", line 681, in execute
    who = eval_who(self.who, self.who_fast)
  File "renpy/ast.py", line 574, in eval_who
    raise Exception("Sayer '%s' is not defined." % who)
Exception: Sayer 'lecturer' is not defined.

Windows-10-10.0.22621
Ren'Py 7.4.11.2266
MAG 1.0
Sun Jan 21 12:03:47 2024
